export const addEntry = async function ({ commit, dispatch }, params) {
  try {

  } catch (e) {
    console.error('An error ocurred while trying to add Entry', e)
    throw new Error(e)
  }
}
export const delEntry = async function ({ commit, dispatch }, params) {
  try {

  } catch (e) {
    console.error('An error ocurred while trying to delete Entry', e)
    throw new Error(e)
  }
}
export const editEntry = async function ({ commit, dispatch }, params) {
  try {

  } catch (e) {
    console.error('An error ocurred while trying to edit Entry', e)
    throw new Error(e)
  }
}

export const initDao = async function ({ commit, dispatch }, params) {
  try {

  } catch (e) {
    console.error('An error ocurred while trying to init Dao', e)
    throw new Error(e)
  }
}

export const reset = async function ({ commit, dispatch }, params) {
  try {

  } catch (e) {
    console.error('An error ocurred while trying to reset', e)
    throw new Error(e)
  }
}

export const getDocuments = async function ({ commit, dispatch }, params) {
  try {

  } catch (e) {
    console.error('An error ocurred while trying to reset', e)
    throw new Error(e)
  }
}

export const getEdges = async function ({ commit, dispatch }, params) {
  try {

  } catch (e) {
    console.error('An error ocurred while trying to reset', e)
    throw new Error(e)
  }
}
